/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.spv.recursos.componentes.animacion;

import java.awt.Component;

/**
 *
 * @author Jaasiel
 */
public class DlgProceso extends javax.swing.JDialog {

    private static DlgProceso dlgProceso;

    /**
     * Creates new form DlgProceso
     */
    private DlgProceso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * muestra un dialogo indicando un proceso en marcha y se le da el
     * componente padre como argumento
     *
     * @param padre
     */
    public static void mostrarDlgProceso(Component padre) {
        if (dlgProceso == null) {
            dlgProceso = new DlgProceso(null, true);
        }

        dlgProceso.setSize(padre.getSize());
        dlgProceso.setLocationRelativeTo(padre);
        dlgProceso.setVisible(true);
    }

    /**
     * muestra un dialogo indicando un proceso en marcha y se le da el
     * componente padre y el texto que aparece en dialogo
     *
     * @param padre
     * @param txt
     */
    public static void mostrarDlgProceso(Component padre, String txt) {
        if (dlgProceso == null) {
            dlgProceso = new DlgProceso(null, true);
        }

        dlgProceso.setSize(padre.getSize());
        dlgProceso.setLocationRelativeTo(padre);
        dlgProceso.lblProceso.setText(txt);
        dlgProceso.setVisible(true);
    }

    /**
     * ocultar el dialogo del proceso
     */
    public static void ocultarDlgProceso() {
        if (dlgProceso == null) {
            dlgProceso = new DlgProceso(null, true);
        }
        dlgProceso.dispose();
    }

    public static void publicar(String txt) {
        if (dlgProceso == null) {
            dlgProceso = new DlgProceso(null, true);
        }
        dlgProceso.lblProceso.setText("<html><h2>" + txt + "</h2>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.8F);

        lblProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ezgif.com-gif-maker-48.gif"))); // NOI18N
        lblProceso.setText("<html><h2>Procesando...</h2>");
        getContentPane().add(lblProceso, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblProceso;
    // End of variables declaration//GEN-END:variables
}
